services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PHP_VERSION=8.1
    restart: always
    entrypoint:
      - /bin/sh
      - -c
      - |
        usermod -u $${UID} www-data
        groupmod -g $${GID} www-data
        /usr/local/bin/docker-entrypoint.sh apache2-foreground
    ports:
      - "9092:80"
    environment:
      PUID: 1000
      PGID: 1000
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: "${DB_USER:-user}"
      WORDPRESS_DB_PASSWORD: "${DB_PASS?error}"
      WORDPRESS_DB_NAME: "${DB_NAME:-database}"
    volumes:
      - ./uploads:/var/www/html/wp-content/uploads:z
      - ./plugins:/var/www/html/wp-content/plugins:z
      - ./themes:/var/www/html/wp-content/themes:z
      - ./wordpress.ini:/usr/local/etc/php/conf.d/wordpress.ini:z
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - "9091:8080"
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_NAME:-database}"
      MYSQL_USER: "${DB_USER:-user}"
      MYSQL_PASSWORD: "${DB_PASS?error}"
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql:z

volumes:
  db:
