services:  
  caddy:
    image: caddy
    ports:
      - "${WP_PORT:-8080}:80"
    restart: always
    volumes:
      - ./caddy:/etc/caddy:z
      - ./caddy_data:/data:z
      - ./logs:/var/log/caddy/:z
      - wordpress:/srv:ro,z
      - ./uploads:/srv/wp-content/uploads:ro,z
      - ./plugins:/srv/wp-content/plugins:ro,z
      - ./themes:/srv/wp-content/themes:ro,z
    depends_on:
      - wordpress
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PHP_VER=8.3
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: "${DB_USER:-user}"
      WORDPRESS_DB_PASSWORD: "${DB_PASS?error}"
      WORDPRESS_DB_NAME: "${DB_NAME:-database}"
    volumes:
      - wordpress:/var/www/html:z
      - ./uploads:/var/www/html/wp-content/uploads:z
      - ./plugins:/var/www/html/wp-content/plugins:z
      - ./themes:/var/www/html/wp-content/themes:z
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT:-9091}:8080"
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_NAME:-database}"
      MYSQL_USER: "${DB_USER:-user}"
      MYSQL_PASSWORD: "${DB_PASS?error}"
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql:z
      - ./mysql-conf:/etc/mysql/conf.d:ro,z

volumes:
  db:
  wordpress:
